require: 
  - rubocop-rails 
AllCops: 
  TargetRubyVersion: 3.1.2 
  NewCops: enable
  Exclude: 
    - 'config.ru' 
    - 'bin/**' 
    - 'lib/**' 
    - 'db/**/*' 
    - 'config/**/*' 
    - 'script/**/*' 
    - !ruby/regexp /old_and_unused\.rb$/ 
Rails: 
  Enabled: true 

Style/FrozenStringLiteralComment: 
  Enabled: false 

#Windowsの改行コードを変更 
Layout/EndOfLine:
  EnforcedStyle: crlf
